### ISSUE TITLE
有相关api文档吗

### ISSUE THREAD

**Issue by ihtml5** [otakustay/react-track#7]
很赞的库，有相关api文档吗

**Comment by otakustay** [comment]
我明天整理一下，把我们团队内部在用的一些总结性内容放上来 @hy-pillow

**Comment by otakustay** [comment]
先临时把我们的参考文档放这边，周末的时候整理下API文档

# react-track接入文档

## 接入步骤

1.确定要采集的具体信息（`collect`）

```js
import {browser, context, session} from '@ecomfe/react-track';

const collect = combineCollects(
    context({...}), // 固定要发送的任何数据
    browser(), // 浏览器的信息，包括UA等
    session() // 追踪单次登录的key
);
```

> `相关代码片段`
> 
	import { combineCollects, browser, context, session} from '@ecomfe/react-track';
	getTrackerCollect = createSelector(
		props => props.username,
		username => {
		    const appContext = {
		        app: 'engmap',
		        username: username,
		        version: $build.version + '@' + $build.time,
		        environment: $build.target
		    };
		    return combineCollects(
		        context(appContext),
		        browser(),
		        session()
		    );
		}
	)
	const collect = this.getTrackerCollect(this.state);

2.确定数据要发送的地址 （`provider`）

```js
import {print} from '@ecomfe/react-track';

// print是一个把信息打印在console中的provider，其它情况也可以自己实现
const trackProvider = print();

如下是一个最基本的把信息侧耳发票POST请求发到服务器去的provider

```
> `相关代码片段1`
> 
	const post = url => {
	    return {
	        install: noop,
	        uninstall: noop,
	        trackPageView: createLogPost(url, 'pageView'),
	        trackEvent: createLogPost(url, 'event')
	    };
    };

> `相关代码片段2`
> 
	import axios from 'axios';
	export const createLogPost = (url, type) => payload => {
	    const body = 'data=' + JSON.stringify({type, payload});
	    axios.post(
	        url,
	        body,
	        {
	            headers: {
	                'Content-Type': 'application/x-www-form-urlencoded'
	            }
	        }
	    );
	};

3.把`collect`和`trackProvide`作为props传给`<Tracker />`

`Tracker` 包裹在BrowserRouter的外层，为应用中所有组件提供收集数据所需要的props
保证后面`TrackRoute`、`TrackEvent`的正常使用

```js
import {Tracker} from '@ecomfe/react-track';

<Tracker collect={collect} provider={trackProvider}>
    <BrowserRouter>
        <Root username={username} filterType={filterType} onSwitchFilterType={onSwitchFilterType} />
    </BrowserRouter>
</Tracker>
```

4.替换现在的路由使用`TrackRoute`统计页面数据（同时替代原有Route的作用）

```js
...
 <Switch>
    <Route path={`${match.url}/review`} exact component={HealthReviewSummary} />
    <Route path={`${match.url}/review/detail`} exact component={HealthReviewDetail} />
    <Route path={`${match.url}/codeline`} exact component={CodelineMain} />
    <Route path={`${match.url}/duplicatefile`} exact component={DuplicateFileMain} />
    <Redirect to={`${match.url}/codeline`} />
</Switch>
...
```

替换为

```js
import {TrackRoute} from '@ecomfe/react-track';
...
<Switch>
    <TrackRoute path={`${match.url}/review`} exact component={HealthReviewSummary} />
    <TrackRoute path={`${match.url}/review/detail`} exact component={HealthReviewDetail} />
    <TrackRoute path={`${match.url}/codeline`} exact component={CodelineMain} />
    <TrackRoute path={`${match.url}/duplicatefile`} exact component={DuplicateFileMain} />
    <Redirect to={`${match.url}/codeline`} />
</Switch>
...
```

5.使用`TrackEvent`包裹需要收集事件数据的组件或者DOM

`组件`
```js
import {TrackEvent} from '@ecomfe/react-track';

const renderIndicator = indicator => {
	...
	return (
	   <TrackEvent
	        key={indicatorType}
	        eventPropName="onSelect"
	        category="indicator"
	        action="click"
	        label={indicatorType}
	    >
	        <Indicator
	            showDetail={showDetail}
	            onSelect={onSelect}
	            onUnselect={onUnselect}
	            activeState={activeState}
	            styleName={styleName}
	            {...indicator}
	        />
	    </TrackEvent>
	);
};
```

DOM

```js
import {TrackEvent} from '@ecomfe/react-track';

const NavItem = ({name, to}) => (
    <TrackEvent eventPropName="onMouseEnter" category="navigation" action="hover" label={name}>
        <li>
            <NavLink exact to={to} activeClassName="nav-link-active">{name}</NavLink>
        </li>
    </TrackEvent>
);
```

**Comment by ihtml5** [comment]
感谢 @otakustay  我研究下

**Comment by otakustay** [comment]
Closed via e5618588a5fc14ce9eabb01886980eab57836331
